// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.10
// source: joon/joon.proto

package joon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JoonServiceClient is the client API for JoonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JoonServiceClient interface {
	HasRole(ctx context.Context, in *HasRoleReq, opts ...grpc.CallOption) (*HasRoleRes, error)
}

type joonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJoonServiceClient(cc grpc.ClientConnInterface) JoonServiceClient {
	return &joonServiceClient{cc}
}

func (c *joonServiceClient) HasRole(ctx context.Context, in *HasRoleReq, opts ...grpc.CallOption) (*HasRoleRes, error) {
	out := new(HasRoleRes)
	err := c.cc.Invoke(ctx, "/joon.JoonService/HasRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JoonServiceServer is the server API for JoonService service.
// All implementations must embed UnimplementedJoonServiceServer
// for forward compatibility
type JoonServiceServer interface {
	HasRole(context.Context, *HasRoleReq) (*HasRoleRes, error)
	mustEmbedUnimplementedJoonServiceServer()
}

// UnimplementedJoonServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJoonServiceServer struct {
}

func (UnimplementedJoonServiceServer) HasRole(context.Context, *HasRoleReq) (*HasRoleRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasRole not implemented")
}
func (UnimplementedJoonServiceServer) mustEmbedUnimplementedJoonServiceServer() {}

// UnsafeJoonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JoonServiceServer will
// result in compilation errors.
type UnsafeJoonServiceServer interface {
	mustEmbedUnimplementedJoonServiceServer()
}

func RegisterJoonServiceServer(s grpc.ServiceRegistrar, srv JoonServiceServer) {
	s.RegisterService(&JoonService_ServiceDesc, srv)
}

func _JoonService_HasRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JoonServiceServer).HasRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/joon.JoonService/HasRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JoonServiceServer).HasRole(ctx, req.(*HasRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

// JoonService_ServiceDesc is the grpc.ServiceDesc for JoonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JoonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "joon.JoonService",
	HandlerType: (*JoonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HasRole",
			Handler:    _JoonService_HasRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "joon/joon.proto",
}
